import '../globals.css';
import Link from 'next/link';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children, modal }) {
    return (
        <html lang="en">
            <body>
                <nav>
                    <ul>
                        <li>
                            <Link href={'/'}>Home</Link>
                        </li>
                        <li>
                            <Link href={'/about'}>About</Link>
                        </li>
                        <li>
                            <Link href={'/blog'}>Blog</Link>
                        </li>
                        <li>
                            <Link href={'/contact'}>Contact</Link>
                        </li>
                        <li>
                            <Link href={'/user'}>User</Link>
                        </li>
                        <li>
                            <Link href={'/archive'}>Archive</Link>
                        </li>
                        <li>
                            <Link href={'/news'}>News</Link>
                        </li>
                        <li>
                            <Link href={'/messages'}>Messages</Link>
                        </li>
                    </ul>
                </nav>
                <main>{children}</main>
                {modal}
                <div id="modal-root" />
            </body>
        </html>
    );
}
