import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Viktor's page project</title>
                <meta name="description" content="Generated by create next app 523" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Hello there</h1>
            </main>
        </>
    );
}
